### ISSUE TITLE
'No module named issue' when running mqttwarn on Python 3.8.10

### ISSUE THREAD

**Issue by pdt590** [mqtt-tools/mqttwarn#699]
- Python 3.8.10
- pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

```
Traceback (most recent call last):
  File "/home/akila/.local/lib/python3.8/site-packages/mqttwarn/util.py", line 6, in <module>
    from importlib.resources import files as resource_files  # type: ignore[attr-defined]
ImportError: cannot import name 'files' from 'importlib.resources' (/usr/lib/python3.8/importlib/resources.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akila/.local/bin/mqttwarn", line 5, in <module>
    from mqttwarn.commands import run
  File "/home/akila/.local/lib/python3.8/site-packages/mqttwarn/commands.py", line 16, in <module>
    from mqttwarn.configuration import Config, load_configuration
  File "/home/akila/.local/lib/python3.8/site-packages/mqttwarn/configuration.py", line 12, in <module>
    from mqttwarn.util import load_functions
  File "/home/akila/.local/lib/python3.8/site-packages/mqttwarn/util.py", line 8, in <module>
    from importlib_resources import files as resource_files  # type: ignore[no-redef]
ModuleNotFoundError: No module named 'importlib_resources'

```
Can you help me to clarify this issue?
Thank you

**Comment by amotl** [comment]
Hi Phan. Apologies for the late reply. We think a01a3313d32 fixed the problem. A new release has been published with v0.36.0. Can you check if the installation works well for you again?

**Comment by amotl** [comment]
Hi again. I think that snippet is enough proof that the flaw was fixed in the most recent release. Closing.

```shell
$ uvx --python=3.8 mqttwarn --version
mqttwarn 0.36.1
```
